# Generated by Django 2.2.5 on 2020-05-26 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomtype',
            name='subtitle',
        ),
        migrations.AddField(
            model_name='roomtype',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
