# Generated by Django 2.2.5 on 2020-05-26 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_auto_20200527_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='subtitle',
            field=models.CharField(default='', max_length=80),
            preserve_default=False,
        ),
    ]
