# Generated by Django 2.2.5 on 2021-01-18 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_auto_20200531_0048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='House_rules',
            new_name='house_rules',
        ),
    ]
