# Generated by Django 2.2.5 on 2021-01-18 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_auto_20210119_0003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='house_rules',
        ),
        migrations.AddField(
            model_name='room',
            name='House_rules',
            field=models.ManyToManyField(blank=True, to='rooms.HouseRule'),
        ),
    ]
