# Generated by Django 2.2.5 on 2021-01-18 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0009_auto_20210119_0011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='House_rules',
            new_name='house_rules',
        ),
    ]
