# Generated by Django 2.2.5 on 2021-01-23 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="message", name="Conversation",),
        migrations.AddField(
            model_name="message",
            name="conversation",
            field=models.ForeignKey(
                # # default=django.utils.timezone.now,
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="conversations.Conversation",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="message",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
