# Generated by Django 2.2.5 on 2021-01-23 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0021_auto_20210123_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('cancled', 'Cancled'), ('pending', 'Pending')], default='pending', max_length=12),
        ),
    ]
