# Generated by Django 2.2.5 on 2021-01-23 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0047_auto_20210124_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('cancled', 'Cancled'), ('confirmed', 'Confirmed')], default='pending', max_length=12),
        ),
    ]
