# Generated by Django 2.2.5 on 2021-01-20 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20210120_1445'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='accurancy',
            new_name='accuracy',
        ),
    ]
